defaults:
  #  - base_config
  - _self_
  - override hydra/launcher: joblib

benchmark_path: ???
material_identifier: ???
optimization:
  objectives: ???
  population_size: 500
  offspring_size: 30
  max_evaluations: 1000000
  variable_count: 100
  precondition_population: false
  write_fronts: false
system:
  v_max: 1
plot_server: none
simulation:
  ppm3: 1
reference_front_file:

hydra:
  job:
    chdir: true
  launcher:
    n_jobs: 8
  sweep:
    dir: multirun/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
